### ISSUE TITLE
[bug] Duplicate error message shown 

### ISSUE THREAD

**Issue by sujaya-sys** [score-spec/score-humanitec#29]
**Describe the bug**
The error output on score-humanitec is a little messy. It starts with the error message, then the help text and then the error message again it seems.

```
$ score-humanitec run --env development
Error: validating workload spec: 1 error(s) decoding:

* 'Resources[db].Properties[name]' expected a map, got 'string'
Usage:
  score-humanitec run [flags]

Flags:
      --env string          Environment ID
      --extensions string   Extensions file (default "./humanitec.score.yaml")
  -f, --file string         Source SCORE file (default "./score.yaml")
  -h, --help                help for run
      --overrides string    Overrides file (default "./overrides.score.yaml")
      --verbose             Enable diagnostic messages (written to STDERR)

validating workload spec: 1 error(s) decoding:

* 'Resources[db].Properties[name]' expected a map, got 'string'
```

We probably don't need to show the help text here.

**Additional context**
Reach out to Will Overton (https://github.com/williamoverton) for further context, who initially reported this issue.

**Comment by ghen** [comment]
The first output is written into `stderr`, where the "help" message is a standard output produced for the User and written into `stdin`.

I would agree that we are better to supress the "help" message on application errors, and only show it if there is a usage error.
