### ISSUE TITLE
Allow custom description when creating new deltas

### ISSUE THREAD

**Issue by ghen** [score-spec/score-humanitec#32]
When new delta is created with `score-humanitec delta` command, it has a hardcoded name (description): "Auto-deployment (SCORE)".

The user would want to customize this message to include the reason for the deployment and, likely, a new version of the workload.

The proposal is to add an extra parameter to the `delta` command to allow custom description for the delta:
  -m  (--message)  string        Overrides description for a newly created delta. Defaults is "Auto-deployment (SCORE)".

**Comment by sujaya-sys** [comment]
Clemens provided some feedback related to this issue:

It'll be great if Score could accommodate different deployment workflows i.e. users would be able to compose their releases. For example: By adding changes to a specific draft (with a specific name that acts as an identifier for a release) users would be able to construct their releases. This comes in handy when wanting to deploy 3 different feature branches individually for example.

**Comment by mathieu-benoit** [comment]
FYI: even with the release of https://github.com/score-spec/score-humanitec/releases/tag/0.7.0, there is still an issue, working on a fix.
